# Generated by Django 5.2.4 on 2025-08-05 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(auto_now_add=True, verbose_name='Data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('em andamento', 'Em andamento'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], max_length=15, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='orcamentos.orcamento')),
            ],
        ),
    ]
