# Generated by Django 5.2.4 on 2025-08-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de vencimento'),
        ),
    ]
