# Generated by Django 5.2.4 on 2025-08-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('numero_faturamentos', models.PositiveIntegerField(verbose_name='Número de faturamentos')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Orcamento',
                'verbose_name_plural': 'Orcamentos',
                'db_table': 'tb_orcamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
