# Generated by Django 5.2.4 on 2025-08-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'verbose_name': 'Orcamento', 'verbose_name_plural': 'Orcamentos'},
        ),
    ]
