# Generated by Django 5.2.4 on 2025-08-06 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('orcamentos', '0002_alter_orcamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='eventos.evento'),
        ),
    ]
